import type { Locale3 } from "./projects";

export interface GlossaryTerm {
  id: string;
  term: Record<Locale3, string>;
  def: Record<Locale3, string>;
}

const t = (en: string, ar: string, fr: string): Record<Locale3, string> => ({ en, ar, fr });

/** Neutral educational definitions of standard infrastructure-finance terms.
 *  Not legal or investment advice; generic industry usage. */
export const GLOSSARY: GlossaryTerm[] = [
  { id: "ppp", term: t("PPP — Public-Private Partnership", "شراكة القطاعين العام والخاص", "PPP — Partenariat Public-Privé"), def: t("A long-term contract between a public authority and a private party in which the private party delivers and operates an asset or service, sharing risks and rewards.", "عقد طويل الأمد بين جهة عامة وطرف خاص يتولى فيه الطرف الخاص تنفيذ وتشغيل أصل أو خدمة، مع تقاسم المخاطر والمكافآت.", "Contrat de long terme entre une autorité publique et un acteur privé où le privé réalise et exploite un actif ou un service, en partageant risques et bénéfices.") },
  { id: "bot", term: t("BOT — Build-Operate-Transfer", "BOT — البناء والتشغيل ونقل الملكية", "BOT — Build-Operate-Transfer"), def: t("A model where a private partner finances and builds an asset, operates it for a fixed term, then transfers full ownership to the public partner.", "نموذج يموّل فيه الشريك الخاص الأصل ويبنيه ويشغّله لمدة محددة، ثم ينقل ملكيته الكاملة إلى الشريك العام.", "Modèle où le partenaire privé finance et construit l'actif, l'exploite pour une durée déterminée, puis en transfère la pleine propriété au partenaire public.") },
  { id: "boot", term: t("BOOT — Build-Own-Operate-Transfer", "BOOT — البناء والملكية والتشغيل ونقل الملكية", "BOOT — Build-Own-Operate-Transfer"), def: t("A BOT variant in which the private partner also holds ownership of the asset during the operating term.", "صيغة من BOT يحتفظ فيها الشريك الخاص بملكية الأصل طوال فترة التشغيل.", "Variante du BOT où le privé détient aussi la propriété de l'actif pendant l'exploitation.") },
  { id: "dbfom", term: t("DBFOM — Design-Build-Finance-Operate-Maintain", "DBFOM — التصميم والبناء والتمويل والتشغيل والصيانة", "DBFOM — Conception-Construction-Financement-Exploitation-Maintenance"), def: t("An integrated model bundling design, construction, financing, operations, and maintenance under one contract.", "نموذج متكامل يجمع التصميم والبناء والتمويل والتشغيل والصيانة في عقد واحد.", "Modèle intégré regroupant conception, construction, financement, exploitation et maintenance dans un seul contrat.") },
  { id: "epc", term: t("EPC — Engineering, Procurement, Construction", "EPC — الهندسة والتوريد والإنشاء", "EPC — Ingénierie, Approvisionnement, Construction"), def: t("A turnkey construction contract where the contractor delivers a completed facility at a fixed price and date.", "عقد إنشاء مفتاح يسلّم فيه المقاول منشأة مكتملة بسعر وتاريخ ثابتين.", "Contrat clé en main où l'entrepreneur livre une installation achevée à prix et date fixes.") },
  { id: "epcf", term: t("EPC+F — EPC with Financing", "EPC+F — الهندسة والتوريد والإنشاء مع التمويل", "EPC+F — EPC avec Financement"), def: t("An EPC contract paired with financing arranged by the contractor or its partners, common in development markets.", "عقد EPC مقترناً بتمويل يرتبه المقاول أو شركاؤه، وشائع في أسواق التنمية.", "Contrat EPC associé à un financement organisé par l'entrepreneur ou ses partenaires, courant dans les marchés du développement.") },
  { id: "spv", term: t("SPV — Special Purpose Vehicle", "SPV — شركة ذات غرض خاص", "SPV — Société de Projet"), def: t("A legally separate company created for a single project, holding its contracts, assets, and financing.", "شركة مستقلة قانوناً تُنشأ لمشروع واحد، وتحمل عقوده وأصوله وتمويله.", "Société juridiquement distincte créée pour un projet unique, portant ses contrats, actifs et financements.") },
  { id: "concession", term: t("Concession", "امتياز", "Concession"), def: t("A contractual right granted to a private party to operate a public service or asset for a defined period.", "حق تعاقدي يُمنح لطرف خاص لتشغيل خدمة عامة أو أصل لمدة محددة.", "Droit contractuel accordé à un acteur privé d'exploiter un service public ou un actif pour une période définie.") },
  { id: "concessionaire", term: t("Concessionaire", "الامتيازي", "Concessionnaire"), def: t("The private company holding a concession and responsible for operating the asset or service.", "الشركة الخاصة الحاملة للامتياز والمسؤولة عن تشغيل الأصل أو الخدمة.", "La société privée titulaire de la concession, responsable de l'exploitation.") },
  { id: "grantor", term: t("Grantor", "المانح للامتياز", "Autorité concédante"), def: t("The public authority that grants a concession and represents the public interest in the contract.", "الجهة العامة التي تمنح الامتياز وتمثل المصلحة العامة في العقد.", "L'autorité publique qui accorde la concession et représente l'intérêt général.") },
  { id: "offtake", term: t("Off-take Agreement", "اتفاقية شراء الإنتاج", "Contrat d'Achat de Production"), def: t("A long-term contract in which a buyer commits to purchase the project's output (power, water, produce), securing revenue.", "عقد طويل الأمد يلتزم فيه مشترٍ بشراء إنتاج المشروع (كهرباء، ماء، محاصيل) بما يضمن الإيراد.", "Contrat à long terme par lequel un acheteur s'engage à acheter la production du projet, sécurisant les revenus.") },
  { id: "tariff", term: t("Tariff", "التعرفة", "Tarif"), def: t("The regulated price users or the public authority pay for the service the project delivers.", "السعر المنظّم الذي يدفعه المستخدمون أو الجهة العامة مقابل خدمة المشروع.", "Prix régulé payé par les usagers ou l'autorité publique pour le service du projet.") },
  { id: "financial-close", term: t("Financial Close", "الإغلاق المالي", "Bouclage Financier"), def: t("The point where all financing contracts are signed and conditions met, so funds can be drawn and construction begin.", "اللحظة التي تُوقّع فيها كل عقود التمويل وتتحقق شروطها، فيمكن سحب الأموال وبدء الإنشاء.", "Le moment où tous les contrats de financement sont signés et leurs conditions remplies, permettant le déblocage des fonds.") },
  { id: "bankability", term: t("Bankability", "القابلية للتمويل", "Finançabilité"), def: t("The degree to which a project's revenues, risks, and contracts satisfy lenders' requirements for financing.", "مدى استيفاء إيرادات المشروع ومخاطره وعقوده لمتطلبات الممولين.", "Mesure dans laquelle les revenus, risques et contrats du projet satisfont les exigences des prêteurs.") },
  { id: "capital-stack", term: t("Capital Stack", "هيكل رأس المال", "Structure du Capital"), def: t("The layered financing of a project: equity, mezzanine, and senior debt, ranked by repayment priority.", "طبقات تمويل المشروع: حقوق ملكية ودين وسط وأولى، مرتبة حسب أولوية السداد.", "Les couches de financement d'un projet : capitaux propres, dette mezzanine et dette senior, par priorité de remboursement.") },
  { id: "equity", term: t("Equity", "حقوق الملكية", "Capitaux Propres"), def: t("The sponsors' own investment in the project, repaid last but carrying ownership and upside.", "استثمار الرعاة الخاص في المشروع، يُسدد أخيراً لكنه يحمل الملكية والمكاسب.", "L'investissement propre des promoteurs, remboursé en dernier mais porteur de propriété et de gains.") },
  { id: "senior-debt", term: t("Senior Debt", "الدين الأول", "Dette Senior"), def: t("Loans repaid first from project revenues, typically secured by the project's assets and contracts.", "قروض تُسدد أولاً من إيرادات المشروع، وعادةً مضمونة بأصوله وعقوده.", "Prêts remboursés en premier sur les revenus du projet, généralement garantis par ses actifs et contrats.") },
  { id: "mezzanine", term: t("Mezzanine Debt", "الدين الأوسط", "Dette Mezzanine"), def: t("Financing ranked between senior debt and equity, carrying higher risk and return.", "تمويل يقع بين الدين الأول وحقوق الملكية، بمخاطر وعوائد أعلى.", "Financement placé entre la dette senior et les capitaux propres, plus risqué et plus rémunérateur.") },
  { id: "sovereign-guarantee", term: t("Sovereign Guarantee", "الضمان السيادي", "Garantie Souveraine"), def: t("A government commitment to cover specified payment obligations if the primary party defaults.", "التزام حكومي بتغطية التزامات دفع محددة إذا أخلّ الطرف الأساسي بالسداد.", "Engagement gouvernemental de couvrir des obligations de paiement définies en cas de défaillance.") },
  { id: "vgf", term: t("VGF — Viability Gap Funding", "VGF — تمويل فجوة الجدوى", "VGF — Financement de l'Écart de Viabilité"), def: t("One-time public capital support that makes a socially valuable project financially viable.", "دعم رأسمالي عام لمرة واحدة يجعل مشروعاً ذا قيمة اجتماعية مجدياً مالياً.", "Soutien en capital public ponctuel rendant financièrement viable un projet d'intérêt social.") },
  { id: "availability-payment", term: t("Availability Payment", "دفعة التوفر", "Paiement de Disponibilité"), def: t("Regular public payments to a private operator for keeping an asset available to standard, independent of usage.", "مدفوعات دورية عامة للمشغل الخاص مقابل إبقاء الأصل متاحاً وفق المعيار، بغض النظر عن الاستخدام.", "Paiements publics réguliers à l'opérateur pour maintenir l'actif disponible au standard, indépendamment de l'usage.") },
  { id: "performance-bond", term: t("Performance Bond", "سند الأداء", "Caution de Bonne Exécution"), def: t("A bank guarantee compensating the client if the contractor fails to meet contractual obligations.", "ضمان بنكي يعوّض المالك إذا أخلّ المقاول بالتزاماته التعاقدية.", "Garantie bancaire compensant le client si l'entrepreneur ne respecte pas ses engagements.") },
  { id: "due-diligence", term: t("Due Diligence", "العناية الواجبة", "Diligence Raisonnable"), def: t("The structured investigation of a project's legal, financial, technical, and environmental standing before commitment.", "الفحص المنظم للوضع القانوني والمالي والفني والبيئي للمشروع قبل الالتزام.", "Examen structuré de la situation juridique, financière, technique et environnementale avant tout engagement.") },
  { id: "feasibility", term: t("Feasibility Study", "دراسة الجدوى", "Étude de Faisabilité"), def: t("An assessment of whether a project is technically possible, economically sound, and environmentally acceptable.", "تقييم ما إذا كان المشروع ممكناً تقنياً وسليماً اقتصادياً ومقبولاً بيئياً.", "Évaluation de la possibilité technique, de la solidité économique et de l'acceptabilité environnementale d'un projet.") },
  { id: "esia", term: t("ESIA — Environmental & Social Impact Assessment", "ESIA — تقييم الأثر البيئي والاجتماعي", "ESIA — Évaluation d'Impact Environnemental et Social"), def: t("A systematic study of a project's environmental and social effects, and the plans to manage them.", "دراسة منهجية للآثار البيئية والاجتماعية للمشروع وخطط إدارتها.", "Étude systématique des effets environnementaux et sociaux d'un projet et des plans pour les gérer.") },
  { id: "esms", term: t("ESMS — Environmental & Social Management System", "ESMS — نظام الإدارة البيئية والاجتماعية", "ESMS — Système de Gestion Environnementale et Sociale"), def: t("The ongoing policies and procedures used to manage environmental and social risks through a project's life.", "السياسات والإجراءات المستمرة لإدارة المخاطر البيئية والاجتماعية طوال عمر المشروع.", "Politiques et procédures continues pour gérer les risques environnementaux et sociaux sur la vie du projet.") },
  { id: "kyc", term: t("KYC — Know Your Customer", "KYC — اعرف عميلك", "KYC — Connaissance Client"), def: t("Identity and background checks required before entering financial or contractual relationships.", "فحوص الهوية والخلفية المطلوبة قبل الدخول في علاقات مالية أو تعاقدية.", "Vérifications d'identité et d'antécédents requises avant toute relation financière ou contractuelle.") },
  { id: "aml", term: t("AML — Anti-Money Laundering", "AML — مكافحة غسل الأموال", "AML — Lutte contre le Blanchiment"), def: t("Rules and screening designed to prevent illicit funds from entering transactions.", "قواعد وفحوص تمنع دخول أموال غير مشروعة إلى المعاملات.", "Règles et filtrages empêchant des fonds illicites d'entrer dans les transactions.") },
  { id: "mrv", term: t("MRV — Measurement, Reporting, Verification", "MRV — القياس والتقرير والتحقق", "MRV — Mesure, Rapportage, Vérification"), def: t("The cycle of measuring performance, reporting it, and having it independently verified.", "دورة قياس الأداء ثم التقرير عنه ثم التحقق منه بشكل مستقل.", "Cycle de mesure de la performance, de rapportage et de vérification indépendante.") },
  { id: "om", term: t("O&M — Operations & Maintenance", "O&M — التشغيل والصيانة", "O&M — Exploitation et Maintenance"), def: t("The day-to-day running and upkeep of an asset during its operating life.", "التشغيل اليومي وصيانة الأصل طوال عمره التشغيلي.", "Exploitation quotidienne et entretien d'un actif pendant sa vie opérationnelle.") },
  { id: "rfp", term: t("RFP — Request for Proposals", "RFP — طلب تقديم العروض", "RFP — Appel à Candidatures"), def: t("A public invitation for qualified parties to submit detailed technical and financial proposals.", "دعوة علنية للأطراف المؤهلة لتقديم عروض فنية ومالية مفصلة.", "Invitation publique aux parties qualifiées de soumettre des propositions techniques et financières détaillées.") },
  { id: "rfq", term: t("RFQ — Request for Qualifications", "RFQ — طلب تأهيل", "RFQ — Appel à Manifestation d'Intérêt"), def: t("A first-stage screening of interested parties' experience and capacity before proposals are invited.", "فرز أولي لخبرة وقدرة الأطراف المهتمة قبل دعوتهم لتقديم العروض.", "Présélection de l'expérience et de la capacité des parties avant l'appel à propositions.") },
  { id: "term-sheet", term: t("Term Sheet", "ورقة الشروط", "Lettre de Conditions"), def: t("A non-binding summary of the main terms a final agreement is expected to contain.", "ملخص غير ملزم لأهم الشروط المتوقع أن يتضمنها الاتفاق النهائي.", "Résumé non contraignant des principales conditions attendues dans l'accord final.") },
  { id: "force-majeure", term: t("Force Majeure", "القوة القاهرة", "Force Majeure"), def: t("Contractual relief for events beyond a party's reasonable control, such as war or natural disaster.", "إعفاء تعاقدي عن أحداث خارج السيطرة المعقولة للطرف، كالحرب أو الكوارث الطبيعية.", "Allègement contractuel pour des événements indépendants de la volonté raisonnable d'une partie.") },
  { id: "handback", term: t("Handback", "التسليم الختامي", "Restitution"), def: t("The transfer of the asset back to the public partner at the end of a concession, in an agreed condition.", "نقل الأصل إلى الشريك العام في نهاية الامتياز وفق حالة متفق عليها.", "Transfert de l'actif au partenaire public en fin de concession, dans un état convenu.") },
  { id: "lock-in", term: t("Lock-in Period", "فترة التقييد", "Période d'Engagement"), def: t("A defined time during which a party cannot sell its stake or exit the project.", "مدة محددة لا يستطيع فيها الطرف بيع حصته أو مغادرة المشروع.", "Durée définie pendant laquelle une partie ne peut céder sa part ni quitter le projet.") },
  { id: "stakeholder", term: t("Stakeholder", "صاحب المصلحة", "Partie Prenante"), def: t("Any party affected by or able to affect the project: communities, regulators, users, lenders.", "أي طرف يتأثر بالمشروع أو يؤثر فيه: المجتمعات والجهات المنظمة والمستخدمون والممولون.", "Toute partie affectée par le projet ou pouvant l'affecter : communautés, régulateurs, usagers, prêteurs.") },
  { id: "land-acquisition", term: t("Land Acquisition", "حيازة الأراضي", "Acquisition Foncière"), def: t("The process of securing land rights for a project, including lawful resettlement where needed.", "عملية تأمين حقوق الأراضي للمشروع، بما يشمل إعادة التوطين القانونية عند الحاجة.", "Processus de sécurisation des droits fonciers, incluant une réinstallation légale si nécessaire.") },
  { id: "grid-interconnection", term: t("Grid Interconnection", "الربط بالشبكة", "Raccordement au Réseau"), def: t("The physical and contractual connection linking a power project to the transmission network.", "الربط المادي والتعاقدي بين مشروع الكهرباء وشبكة النقل.", "Connexion physique et contractuelle reliant un projet électrique au réseau de transport.") },
  { id: "public-consultation", term: t("Public Consultation", "التشاور العام", "Consultation Publique"), def: t("Structured engagement with affected communities and stakeholders during project preparation.", "إشراك منظم للمجتمعات المتأثرة وأصحاب المصلحة أثناء إعداد المشروع.", "Engagement structuré avec les communautés affectées et les parties prenantes durant la préparation.") },
];

export const GLOSSARY_COPY: Record<Locale3, {
  title: string; intro: string; search: string; count: string; noResults: string;
  notice: string; sources: string; sourcesIntro: string; sourcesGovernments: string;
}> = {
  en: {
    title: "PPP & infrastructure glossary", intro: "Standard infrastructure-finance and partnership terms, explained plainly in three languages. Educational reference — not legal or investment advice.",
    search: "Search a term or definition", count: "terms", noResults: "No term matches this search.",
    notice: "Definitions describe common industry usage. Contracts may define terms differently — the signed agreement governs.",
    sources: "Deepen the context", sourcesIntro: "Related institutional pages:",
    sourcesGovernments: "For Governments & Public Institutions",
  },
  ar: {
    title: "معجم مصطلحات الشراكات والبنية التحتية", intro: "مصطلحات قياسية لتمويل البنية التحتية والشراكات، مشروحة ببساطة بثلاث لغات. مرجع تعليمي — وليس استشارة قانونية أو استثمارية.",
    search: "ابحث عن مصطلح أو تعريف", count: "مصطلحاً", noResults: "لا يوجد مصطلح مطابق للبحث.",
    notice: "التعريفات توضح الاستخدام الصناعي الشائع. قد تُعرّف العقود المصطلحات بشكل مختلف — الاتفاق الموقع هو الحاكم.",
    sources: "تعمّق في السياق", sourcesIntro: "صفحات مؤسسية ذات صلة:",
    sourcesGovernments: "للحكومات والمؤسسات العامة",
  },
  fr: {
    title: "Glossaire PPP & infrastructures", intro: "Termes standard du financement d'infrastructures et des partenariats, expliqués simplement en trois langues. Référence éducative — ni conseil juridique ni conseil en investissement.",
    search: "Rechercher un terme ou une définition", count: "termes", noResults: "Aucun terme ne correspond à cette recherche.",
    notice: "Les définitions décrivent l'usage courant du secteur. Les contrats peuvent les définir différemment — l'accord signé prévaut.",
    sources: "Approfondir le contexte", sourcesIntro: "Pages institutionnelles liées :",
    sourcesGovernments: "Pour les gouvernements et institutions publiques",
  },
};
