import type { Locale3 } from "./projects";

const en = {
  eyebrow: "MARKET_VIEW",
  titleTemplate: "{sector} in {country}",
  introTemplate: "Published AIABASD projects and partnership paths at the intersection of {sector} and the {country} corridor. Availability and next steps are confirmed with the project team before any engagement.",
  projectsTitle: "Published projects in this market",
  projectsCount: "projects published",
  noProjects: "No projects published in this exact combination yet. The Alliance develops projects across {country} — bring yours or request an introduction.",
  sectorTitle: "About this sector",
  corridorTitle: "Corridor",
  capitalLabel: "Capital",
  regionLabel: "Region",
  statusLabel: "Status",
  statusActive: "Active corridor",
  statusPipeline: "Pipeline corridor",
  browseSector: "All {sector} opportunities",
  browseCorridor: "The {country} corridor",
  relatedTitle: "Other sectors in {country}",
  ctaSubmit: "Submit a project for this market",
  ctaIntro: "Request an introduction",
  breadcrumbHome: "Home",
  breadcrumbCountry: "Corridors",
};

export const MARKET_COPY: Record<Locale3, typeof en> = {
  en,
  ar: {
    eyebrow: "عرض_السوق",
    titleTemplate: "{sector} في {country}",
    introTemplate: "مشاريع التحالف المنشورة ومسارات الشراكة عند تقاطع {sector} مع ممر {country}. يُؤكد التوفر والخطوات التالية مع فريق المشروع قبل أي التزام.",
    projectsTitle: "المشاريع المنشورة في هذا السوق",
    projectsCount: "مشروعاً منشوراً",
    noProjects: "لا توجد مشاريع منشورة بعد في هذا التقاطع بعينه. يطوّر التحالف مشاريع عبر {country} — قدّم مشروعك أو اطلب تعريفاً.",
    sectorTitle: "عن هذا القطاع",
    corridorTitle: "الممر",
    capitalLabel: "العاصمة",
    regionLabel: "المنطقة",
    statusLabel: "الحالة",
    statusActive: "ممر نشط",
    statusPipeline: "ممر قيد الإعداد",
    browseSector: "كل فرص {sector}",
    browseCorridor: "ممر {country}",
    relatedTitle: "قطاعات أخرى في {country}",
    ctaSubmit: "تقديم مشروع لهذا السوق",
    ctaIntro: "طلب تعريف",
    breadcrumbHome: "الرئيسية",
    breadcrumbCountry: "الممرات",
  },
  fr: {
    eyebrow: "VUE_MARCHÉ",
    titleTemplate: "{sector} au {country}",
    introTemplate: "Projets AIABASD publiés et pistes de partenariat à l'intersection de {sector} et du corridor {country}. La disponibilité et les prochaines étapes sont confirmées avec l'équipe projet avant tout engagement.",
    projectsTitle: "Projets publiés sur ce marché",
    projectsCount: "projets publiés",
    noProjects: "Aucun projet publié dans cette combinaison pour l'instant. L'Alliance développe des projets à travers {country} — proposez le vôtre ou demandez une mise en relation.",
    sectorTitle: "À propos de ce secteur",
    corridorTitle: "Corridor",
    capitalLabel: "Capitale",
    regionLabel: "Région",
    statusLabel: "Statut",
    statusActive: "Corridor actif",
    statusPipeline: "Corridor en préparation",
    browseSector: "Toutes les opportunités {sector}",
    browseCorridor: "Le corridor {country}",
    relatedTitle: "Autres secteurs au {country}",
    ctaSubmit: "Soumettre un projet pour ce marché",
    ctaIntro: "Demander une mise en relation",
    breadcrumbHome: "Accueil",
    breadcrumbCountry: "Corridors",
  },
};
