import type { Locale3 } from "./projects";

const en = {
  directory: "Company network", intro: "Explore the companies listed by AIABASD, review the information available, and request a focused introduction.",
  search: "Search companies or published capabilities", sector: "Published sector", country: "Published country coverage", all: "All", results: "companies", reset: "Clear filters", empty: "No company matches these filters. Try a company name or clear the filters.",
  profile: "View company profile", listing: "Directory listing", listingNote: "A directory listing records the company name and logo. It does not establish technical qualification, registration verification, or an active project appointment.",
  missing: "Not yet published", overview: "Company information", capabilities: "Published capabilities", countries: "Countries served", documents: "Documentary review", identity: "Identity", registration: "Company registration", references: "Project references", reviewNote: "Ask for current supporting information before evaluating suitability for a project.",
  request: "Request an introduction", requestIntro: "Tell AIABASD who you want to meet and what your organization can contribute. Introductions are reviewed before any connection is arranged.",
  targetCompany: "Company to meet", noCompany: "Ask AIABASD to identify a company", targetProject: "Project of interest", noProject: "General cooperation", need: "Published project need", noNeed: "General project discussion",
  organization: "Your organization", name: "Your name", email: "Institutional email", role: "Your role", contribution: "What can your organization contribute?", timeline: "Preferred timeline", language: "Preferred correspondence language", submit: "Send introduction request", sending: "Sending request…", consent: "I am authorized to share these details and agree that AIABASD may contact my organization about this request.",
  error: "The request could not be confirmed. Your details are still here; retry or email contact@aiabasd.org.", invalid: "Check the company, project and project need. One of the linked references is no longer available.", success: "Introduction request received", reference: "Your reference", nextTitle: "What happens next", next: "AIABASD reviews the scope, may ask for supporting information, and discusses whether an introduction is appropriate. This confirmation does not mean the company has accepted the request.", followup: "Follow up by email", another: "Start another request", context: "Your introduction brief", privacy: "Read the privacy policy", required: "Required fields are marked *.",
  needsTitle: "Where your organization could contribute", needsNote: "These are the partnership opportunities in the published project profile. Availability and the next milestone must be confirmed with the project team.", express: "Express interest in this need", reviewed: "Profile last reviewed", noNeeds: "Specific partner needs have not been published. Ask the team for the current requirements.",
  source: "Source", website: "Company website", current: "Current project stage", footer: "Company directory", returnDirectory: "Back to company network",
};

export const NETWORK_COPY: Record<Locale3, typeof en> = {
  en,
  ar: {
    directory: "شبكة الشركات", intro: "تعرّف على الشركات المدرجة لدى التحالف، وراجع المعلومات المتاحة، واطلب تواصلاً موجهاً.",
    search: "ابحث عن شركة أو قدرات منشورة", sector: "القطاع المنشور", country: "نطاق العمل المنشور", all: "الكل", results: "شركة", reset: "مسح المرشحات", empty: "لا توجد شركة تطابق هذه المرشحات. جرّب اسم الشركة أو امسح المرشحات.",
    profile: "عرض ملف الشركة", listing: "إدراج في الدليل", listingNote: "يسجل الإدراج اسم الشركة وشعارها، ولا يثبت التأهيل الفني أو التحقق من التسجيل أو تكليفاً بمشروع قائم.",
    missing: "لم يُنشر بعد", overview: "معلومات الشركة", capabilities: "القدرات المنشورة", countries: "الدول التي تخدمها", documents: "مراجعة المستندات", identity: "الهوية", registration: "تسجيل الشركة", references: "مراجع المشاريع", reviewNote: "اطلب المعلومات الداعمة الحالية قبل تقييم ملاءمة الشركة للمشروع.",
    request: "طلب تعريف بشريك", requestIntro: "أخبر التحالف بمن تريد التواصل معه وما تستطيع مؤسستك تقديمه. تُراجع الطلبات قبل ترتيب أي تواصل.",
    targetCompany: "الشركة المطلوبة", noCompany: "اطلب من التحالف تحديد شركة", targetProject: "المشروع المستهدف", noProject: "تعاون عام", need: "احتياج المشروع المنشور", noNeed: "نقاش عام حول المشروع",
    organization: "مؤسستك", name: "اسمك", email: "البريد المؤسسي", role: "دورك", contribution: "ماذا تستطيع مؤسستك تقديمه؟", timeline: "الإطار الزمني المفضل", language: "لغة المراسلات المفضلة", submit: "إرسال طلب التعريف", sending: "جارٍ إرسال الطلب…", consent: "أنا مخول بمشاركة هذه المعلومات وأوافق على تواصل التحالف مع مؤسستي بشأن هذا الطلب.",
    error: "تعذر تأكيد الطلب. بياناتك ما زالت هنا؛ أعد المحاولة أو راسل contact@aiabasd.org.", invalid: "راجع الشركة والمشروع والاحتياج. أحد المراجع المرتبطة لم يعد متاحاً.", success: "تم استلام طلب التعريف", reference: "رقمك المرجعي", nextTitle: "ماذا يحدث بعد ذلك؟", next: "يراجع التحالف نطاق الطلب، وقد يطلب معلومات داعمة، ويناقش ملاءمة التعريف. لا يعني هذا التأكيد قبول الشركة للطلب.", followup: "المتابعة بالبريد الإلكتروني", another: "بدء طلب آخر", context: "ملخص طلب التعريف", privacy: "قراءة سياسة الخصوصية", required: "الحقول المطلوبة مميزة بعلامة *.",
    needsTitle: "أين يمكن لمؤسستك المساهمة؟", needsNote: "هذه فرص الشراكة المنشورة في ملف المشروع. يجب تأكيد التوفر والمعلم التالي مع فريق المشروع.", express: "إبداء الاهتمام بهذا الاحتياج", reviewed: "آخر مراجعة للملف", noNeeds: "لم تُنشر احتياجات محددة للشركاء. اطلب المتطلبات الحالية من الفريق.",
    source: "المصدر", website: "موقع الشركة", current: "مرحلة المشروع الحالية", footer: "دليل الشركات", returnDirectory: "العودة إلى شبكة الشركات",
  },
  fr: {
    directory: "Réseau d’entreprises", intro: "Découvrez les entreprises répertoriées par l’AIABASD, examinez les informations disponibles et demandez une mise en relation ciblée.",
    search: "Rechercher une entreprise ou des capacités publiées", sector: "Secteur publié", country: "Couverture géographique publiée", all: "Tous", results: "entreprises", reset: "Effacer les filtres", empty: "Aucune entreprise ne correspond. Essayez un nom ou effacez les filtres.",
    profile: "Voir le profil", listing: "Inscription à l’annuaire", listingNote: "Une inscription présente le nom et le logo. Elle ne constitue ni une qualification technique, ni une vérification d’immatriculation, ni une nomination sur un projet actif.",
    missing: "Pas encore publié", overview: "Informations sur l’entreprise", capabilities: "Capacités publiées", countries: "Pays desservis", documents: "Examen documentaire", identity: "Identité", registration: "Immatriculation", references: "Références de projets", reviewNote: "Demandez les justificatifs actuels avant d’évaluer l’adéquation au projet.",
    request: "Demander une mise en relation", requestIntro: "Indiquez à l’AIABASD qui vous souhaitez rencontrer et ce que votre organisation peut apporter. Chaque demande est examinée avant toute mise en relation.",
    targetCompany: "Entreprise à rencontrer", noCompany: "Demander à l’AIABASD d’identifier une entreprise", targetProject: "Projet concerné", noProject: "Coopération générale", need: "Besoin publié du projet", noNeed: "Discussion générale sur le projet",
    organization: "Votre organisation", name: "Votre nom", email: "E-mail institutionnel", role: "Votre rôle", contribution: "Que peut apporter votre organisation ?", timeline: "Calendrier souhaité", language: "Langue de correspondance", submit: "Envoyer la demande", sending: "Envoi en cours…", consent: "Je suis autorisé à partager ces informations et j’accepte que l’AIABASD contacte mon organisation au sujet de cette demande.",
    error: "La demande n’a pas pu être confirmée. Vos informations sont conservées à l’écran ; réessayez ou écrivez à contact@aiabasd.org.", invalid: "Vérifiez l’entreprise, le projet et le besoin. Une référence liée n’est plus disponible.", success: "Demande de mise en relation reçue", reference: "Votre référence", nextTitle: "Prochaines étapes", next: "L’AIABASD examine le périmètre, peut demander des justificatifs et évalue la pertinence d’une mise en relation. Cette confirmation ne signifie pas que l’entreprise a accepté.", followup: "Suivre par e-mail", another: "Nouvelle demande", context: "Votre demande en bref", privacy: "Lire la politique de confidentialité", required: "Les champs obligatoires sont marqués *.",
    needsTitle: "Où votre organisation peut-elle contribuer ?", needsNote: "Voici les opportunités de partenariat du profil publié. Leur disponibilité et le prochain jalon doivent être confirmés auprès de l’équipe projet.", express: "Exprimer un intérêt pour ce besoin", reviewed: "Dernière revue du profil", noNeeds: "Aucun besoin spécifique n’a été publié. Demandez les exigences actuelles à l’équipe.",
    source: "Source", website: "Site de l’entreprise", current: "Étape actuelle du projet", footer: "Annuaire des entreprises", returnDirectory: "Retour au réseau d’entreprises",
  },
};
