import type { Locale3 } from "./projects";

const en = {
  platform: "Member access",
  unavailable: "Member access is not configured on this deployment. Please email gs@aibasd.org.",
  accessTitle: "Member sign-in",
  accessIntro: "Sign in with your institutional email. We send a one-time sign-in link — no passwords.",
  emailLabel: "Institutional email",
  sendLink: "Send sign-in link",
  sending: "Sending…",
  checkEmail: "Check {email} for the sign-in link. Opening it signs you in here.",
  useAnother: "Use a different email",
  failed: "The sign-in link could not be sent. Retry or email gs@aibasd.org.",
  loadFailed: "The room list could not be loaded. Refresh the page or email gs@aibasd.org.",
  signedInAs: "Signed in as",
  continueRooms: "Open your project rooms",
  signOut: "Sign out",
  loading: "Loading…",
  roomsTitle: "Project rooms",
  roomsIntro: "Private workspaces for confirmed collaborations: tasks, documents, and the activity record for each project team.",
  gate: "Sign in to view your project rooms.",
  empty: "No rooms yet. A room is created when a collaboration is confirmed.",
  yourRole: "Your role",
  roleOwner: "Owner",
  roleCoordinator: "Coordinator",
  roleMember: "Member",
  createRoom: "Create a room",
  projectLabel: "Project",
  titleLabel: "Room title",
  create: "Create",
  creating: "Creating…",
  backRooms: "All rooms",
  tasksTitle: "Tasks",
  taskTitle: "Task description",
  add: "Add",
  adding: "Adding…",
  statusOpen: "Open",
  statusInProgress: "In progress",
  statusDone: "Done",
  documentsTitle: "Documents",
  upload: "Upload document",
  uploading: "Uploading…",
  download: "Download",
  remove: "Delete",
  activityTitle: "Activity",
  noTasks: "No tasks yet.",
  noDocuments: "No documents yet.",
  noActivity: "No activity yet.",
  uploadHint: "Files are shared with this project team only. Keep personal identifiers out of filenames.",
  invalidRoom: "This room is not available for your account.",
  inviteTitle: "Workspace invitation",
  inviteIntro: "Accept your AIABASD project-room invitation.",
  accept: "Accept invitation",
  accepting: "Accepting…",
  accepted: "Invitation accepted. You now have access to the workspace.",
  already: "This invitation was already accepted.",
  invalidInvite: "This invitation link is not valid.",
  mismatch: "This invitation was sent to a different email address. Sign in with {email}.",
  inviteFailed: "The invitation could not be accepted. Retry or email gs@aibasd.org.",
  signInFirst: "Sign in to accept this invitation",
  activityTaskAdded: "Task added",
  activityTaskUpdated: "Task updated",
  activityDocumentAdded: "Document uploaded",
  activityDocumentRemoved: "Document deleted",
};

export const ROOMS_COPY: Record<Locale3, typeof en> = {
  en,
  ar: {
    platform: "دخول الأعضاء",
    unavailable: "دخول الأعضاء غير مُهيّأ على هذا النشر. راسلنا على gs@aibasd.org.",
    accessTitle: "تسجيل دخول الأعضاء",
    accessIntro: "سجّل الدخول ببريدك المؤسسي. نرسل رابط دخول لمرة واحدة — دون كلمات مرور.",
    emailLabel: "البريد المؤسسي",
    sendLink: "إرسال رابط الدخول",
    sending: "جارٍ الإرسال…",
    checkEmail: "تحقق من {email} لرابط الدخول. فتحه ي signinك هنا مباشرة.",
    useAnother: "استخدام بريد آخر",
    failed: "تعذر إرسال رابط الدخول. أعد المحاولة أو راسل gs@aibasd.org.",
  loadFailed: "تعذر تحميل قائمة الغرف. حدّث الصفحة أو راسل gs@aibasd.org.",
    signedInAs: "مسجّل الدخول باسم",
    continueRooms: "افتح غرف مشاريعك",
    signOut: "تسجيل الخروج",
    loading: "جارٍ التحميل…",
    roomsTitle: "غرف المشاريع",
    roomsIntro: "مساحات عمل خاصة للتعاونات المؤكدة: المهام والمستندات وسجل النشاط لكل فريق مشروع.",
    gate: "سجّل الدخول لعرض غرف مشاريعك.",
    empty: "لا غرف بعد. تُنشأ الغرفة عند تأكيد التعاون.",
    yourRole: "دورك",
    roleOwner: "مالك",
    roleCoordinator: "منسق",
    roleMember: "عضو",
    createRoom: "إنشاء غرفة",
    projectLabel: "المشروع",
    titleLabel: "عنوان الغرفة",
    create: "إنشاء",
    creating: "جارٍ الإنشاء…",
    backRooms: "كل الغرف",
    tasksTitle: "المهام",
    taskTitle: "وصف المهمة",
    add: "إضافة",
    adding: "جارٍ الإضافة…",
    statusOpen: "مفتوحة",
    statusInProgress: "قيد التنفيذ",
    statusDone: "منجزة",
    documentsTitle: "المستندات",
    upload: "رفع مستند",
    uploading: "جارٍ الرفع…",
    download: "تنزيل",
    remove: "حذف",
    activityTitle: "النشاط",
    noTasks: "لا مهام بعد.",
    noDocuments: "لا مستندات بعد.",
    noActivity: "لا نشاط بعد.",
    uploadHint: "تُشارك الملفات مع فريق هذا المشروع فقط. تجنب بيانات التعريف الشخصية في أسماء الملفات.",
    invalidRoom: "هذه الغرفة غير متاحة لحسابك.",
    inviteTitle: "دعوة مساحة العمل",
    inviteIntro: "اقبل دعوتك إلى غرف مشاريع التحالف.",
    accept: "قبول الدعوة",
    accepting: "جارٍ القبول…",
    accepted: "تم قبول الدعوة. لديك الآن حق الوصول إلى مساحة العمل.",
    already: "تم قبول هذه الدعوة مسبقاً.",
    invalidInvite: "رابط الدعوة غير صالح.",
    mismatch: "أُرسلت هذه الدعوة إلى بريد آخر. سجّل الدخول بـ {email}.",
    inviteFailed: "تعذر قبول الدعوة. أعد المحاولة أو راسل gs@aibasd.org.",
    signInFirst: "سجّل الدخول لقبول هذه الدعوة",
    activityTaskAdded: "أُضيفت مهمة",
    activityTaskUpdated: "حُدثت مهمة",
    activityDocumentAdded: "رُفع مستند",
    activityDocumentRemoved: "حُذف مستند",
  },
  fr: {
    platform: "Accès membres",
    unavailable: "L'accès membre n'est pas configuré sur ce déploiement. Écrivez à gs@aibasd.org.",
    accessTitle: "Connexion membre",
    accessIntro: "Connectez-vous avec votre e-mail institutionnel. Nous envoyons un lien de connexion à usage unique — sans mot de passe.",
    emailLabel: "E-mail institutionnel",
    sendLink: "Envoyer le lien",
    sending: "Envoi…",
    checkEmail: "Consultez {email} pour le lien de connexion. L'ouvrir vous connecte ici.",
    useAnother: "Utiliser un autre e-mail",
    failed: "Le lien n'a pas pu être envoyé. Réessayez ou écrivez à gs@aibasd.org.",
  loadFailed: "La liste des salons n'a pas pu être chargée. Rafraîchissez la page ou écrivez à gs@aibasd.org.",
    signedInAs: "Connecté en tant que",
    continueRooms: "Ouvrir vos salons de projet",
    signOut: "Se déconnecter",
    loading: "Chargement…",
    roomsTitle: "Salons de projet",
    roomsIntro: "Espaces de travail privés pour les collaborations confirmées : tâches, documents et journal d'activité de chaque équipe.",
    gate: "Connectez-vous pour consulter vos salons de projet.",
    empty: "Aucun salon. Un salon est créé lorsqu'une collaboration est confirmée.",
    yourRole: "Votre rôle",
    roleOwner: "Propriétaire",
    roleCoordinator: "Coordinateur",
    roleMember: "Membre",
    createRoom: "Créer un salon",
    projectLabel: "Projet",
    titleLabel: "Titre du salon",
    create: "Créer",
    creating: "Création…",
    backRooms: "Tous les salons",
    tasksTitle: "Tâches",
    taskTitle: "Description de la tâche",
    add: "Ajouter",
    adding: "Ajout…",
    statusOpen: "Ouverte",
    statusInProgress: "En cours",
    statusDone: "Terminée",
    documentsTitle: "Documents",
    upload: "Téléverser un document",
    uploading: "Téléversement…",
    download: "Télécharger",
    remove: "Supprimer",
    activityTitle: "Activité",
    noTasks: "Aucune tâche.",
    noDocuments: "Aucun document.",
    noActivity: "Aucune activité.",
    uploadHint: "Les fichiers sont partagés avec cette équipe uniquement. Évitez les identifiants personnels dans les noms de fichiers.",
    invalidRoom: "Ce salon n'est pas disponible pour votre compte.",
    inviteTitle: "Invitation à l'espace de travail",
    inviteIntro: "Acceptez votre invitation aux salons de projet de l'AIABASD.",
    accept: "Accepter l'invitation",
    accepting: "Acceptation…",
    accepted: "Invitation acceptée. Vous avez accès à l'espace de travail.",
    already: "Cette invitation a déjà été acceptée.",
    invalidInvite: "Ce lien d'invitation n'est pas valide.",
    mismatch: "Cette invitation a été envoyée à une autre adresse. Connectez-vous avec {email}.",
    inviteFailed: "L'invitation n'a pas pu être acceptée. Réessayez ou écrivez à gs@aibasd.org.",
    signInFirst: "Connectez-vous pour accepter cette invitation",
    activityTaskAdded: "Tâche ajoutée",
    activityTaskUpdated: "Tâche mise à jour",
    activityDocumentAdded: "Document téléversé",
    activityDocumentRemoved: "Document supprimé",
  },
};
