export const ALL_ROUTES = [
  "/",
  "/pipeline",
  "/visions",
  "/services",
  "/governments",
  "/intelligence",
  "/match",
  "/gallery",
  "/hama-project",
  "/programs/hama-rehabilitation",
  "/programs/al-arish-hub",
  "/programs/green-energy",
  "/programs/digital-africa",
  "/programs/integrated-cities",
  "/programs/debris-recycling",
  "/programs/food-security",
  "/corridors/gm",
  "/corridors/sl",
  "/corridors/ci",
  "/corridors/bf",
  "/corridors/gh",
  "/corridors/ao",
  "/corridors/sd",
  "/corridors/eg",
  "/corridors/jo",
  "/corridors/sy",
  "/corridors/sa",
  "/team/mohammed-abdel-moneim",
  "/team/faris-safi",
  "/team/ziad-shneikat",
  "/governance/esia-esms",
  "/governance/kyc-aml",
  "/governance/independent-oversight",
  "/governance/contracts",
  "/trust",
  "/privacy",
  "/terms",
  "/404",
  "/investor-portal",
  "/investor-portal/vault",
  "/admin",
  "/impact",
  "/sectors/housing",
  "/sectors/energy",
  "/sectors/infrastructure",
  "/sectors/circular",
  "/sectors/industry",
  "/sectors/agriculture",
  "/sectors/social",
  "/sectors/multi",
  "/projects",
  "/submit-project",
  "/opportunity-map",
  "/projects/sudan-productive-housing",
  "/projects/sudan-reconstruction-vision",
  "/projects/hama-solar-200mw",
  "/projects/hama-debris-recycling",
  "/projects/smart-meters-syria",
  "/projects/dummar-housing",
  "/projects/hama-housing",
  "/projects/schools-health-rehabilitation",
  "/projects/hasiya-industrial-zone",
  "/projects/hama-agriculture-water",
  "/projects/cci-investment-portfolio",
  "/projects/ghana-cooperation-program",
  "/projects/angola-vision",
  "/projects/china-arab-africa-platform",
  "/projects/china-saudi-africa-gateway",
  "/projects/cross-border-trade-platform",
  "/projects/advanced-technology-cooperation",
];

export const PRIVATE_ROUTES = new Set(["/admin", "/investor-portal", "/investor-portal/vault"]);

export const publicRoutes = (isVercel) =>
  isVercel ? ALL_ROUTES.filter((route) => !PRIVATE_ROUTES.has(route)) : ALL_ROUTES;

export const SITEMAP_ROUTES = ALL_ROUTES.filter((route) => route !== "/404" && !PRIVATE_ROUTES.has(route));

export const sitemapRoutes = (isVercel) =>
  isVercel ? SITEMAP_ROUTES.filter((route) => !PRIVATE_ROUTES.has(route)) : SITEMAP_ROUTES;
