const MARKET_SECTORS = ["housing", "energy", "infrastructure", "circular", "industry", "agriculture", "social", "multi"];
const MARKET_ISOS = ["gm", "sl", "ci", "bf", "gh", "ao", "sd", "eg", "jo", "sy", "sa"];

export const ALL_ROUTES = [
  "/",
  "/pipeline",
  "/visions",
  "/services",
  "/governments",
  "/companies",
  "/introductions",
  "/preparation",
  "/access",
  "/rooms",
  "/accept-invite",
  "/glossary",
  "/templates",
  "/verify",
  "/knowledge",
  ...["trilogy", "creation-design-group", "kaolin", "mauritanian-metallogistic", "adfat", "saudi-mauritanian-industrial", "global-agriculture", "saudi-mauritanian-trading", "saudi-mauritanian-investment", "adfat-gold", "nabt", "chemexa", "tyms-contracting", "aacid"].map(slug => `/companies/${slug}`),
  "/intelligence",
  "/match",
  "/gallery",
  "/hama-project",
  "/programs/hama-rehabilitation",
  "/programs/al-arish-hub",
  "/programs/green-energy",
  "/programs/digital-africa",
  "/programs/integrated-cities",
  "/programs/debris-recycling",
  "/programs/food-security",
  "/corridors/gm",
  "/corridors/sl",
  "/corridors/ci",
  "/corridors/bf",
  "/corridors/gh",
  "/corridors/ao",
  "/corridors/sd",
  "/corridors/eg",
  "/corridors/jo",
  "/corridors/sy",
  "/corridors/sa",
  "/team/mohammed-abdel-moneim",
  "/team/faris-safi",
  "/team/ziad-shneikat",
  "/governance/esia-esms",
  "/governance/kyc-aml",
  "/governance/independent-oversight",
  "/governance/contracts",
  "/trust",
  "/privacy",
  "/terms",
  "/404",
  "/investor-portal",
  "/investor-portal/vault",
  "/admin",
  "/impact",
  "/sectors/housing",
  "/sectors/energy",
  "/sectors/infrastructure",
  "/sectors/circular",
  "/sectors/industry",
  "/sectors/agriculture",
  "/sectors/social",
  "/sectors/multi",
  "/projects",
  "/submit-project",
  "/opportunity-map",
  "/projects/sudan-productive-housing",
  "/projects/sudan-reconstruction-vision",
  "/projects/hama-solar-200mw",
  "/projects/hama-debris-recycling",
  "/projects/smart-meters-syria",
  "/projects/dummar-housing",
  "/projects/hama-housing",
  "/projects/schools-health-rehabilitation",
  "/projects/hasiya-industrial-zone",
  "/projects/hama-agriculture-water",
  "/projects/cci-investment-portfolio",
  "/projects/ghana-cooperation-program",
  "/projects/angola-vision",
  "/projects/china-arab-africa-platform",
  "/projects/china-saudi-africa-gateway",
  "/projects/cross-border-trade-platform",
  "/projects/advanced-technology-cooperation",
  ...MARKET_ISOS.flatMap((iso) => MARKET_SECTORS.map((sector) => `/opportunities/${iso}/${sector}`)),
];

export const PRIVATE_ROUTES = new Set(["/admin", "/investor-portal", "/investor-portal/vault"]);

export const publicRoutes = (isVercel) =>
  isVercel ? ALL_ROUTES.filter((route) => !PRIVATE_ROUTES.has(route)) : ALL_ROUTES;

// Basic company records remain available to visitors but are not indexed until
// approved substantive profiles are supplied. Introduction forms are utility pages.
export const SITEMAP_ROUTES = ALL_ROUTES.filter((route) => route !== "/404" && route !== "/introductions" && route !== "/preparation" && route !== "/access" && route !== "/rooms" && route !== "/accept-invite" && !route.startsWith("/companies/") && !PRIVATE_ROUTES.has(route));

export const sitemapRoutes = (isVercel) =>
  isVercel ? SITEMAP_ROUTES.filter((route) => !PRIVATE_ROUTES.has(route)) : SITEMAP_ROUTES;
